export default {
  BotCreateFrom: {
    queRen: '确认',
    quXiao: '取消',
    ma: '吗？',
    ninZhenDeRenXin: '您真的忍心删除',
    shanChuJiQiRen: '删除机器人',
    weiXianCaoZuo: '危险操作',
    kaiChangBaiYuZhi: '开场白预置问题',
    shuRuKaiChangWen: '输入开场文案',
    kaiChangBaiWenAn: '开场白文案',
    kaiChangBai: '开场白',
    shiYongPET: '使用 petercat 提供的 token',
    guanFang: '官方',
    xuanZeTOK: '选择 token',
    xuanZeDaMoXing: '选择大模型',
    daMoXing: '大模型',
    renSheYuHuiFu: '人设与回复逻辑',
    jianDanMiaoShuJi: '简单描述机器人的用途',
    jiQiRenMiaoShu: '机器人描述*',
    geiJiQiRenQi: '给机器人起一个独一无二的名字',
    jiQiRenMingCheng: '机器人名称*',
    gITHU: 'GitHub 头像',
    suiJiTouXiang: '随机头像',
    jiQiRenTouXiang: '机器人头像*',
    ziDingYi: '自定义',
    shanChuShiBaiE: '删除失败 ',
    shanChuChengGong: '删除成功',
  },
  InputList: {
    shanChu: '删除',
    shuRuKaiChangBai: '输入开场白引导问题',
  },
  Knowledge: {
    zhiShiKuWeiKong: '知识库为空',
    zhiShiKuGengXin: '知识库更新中',
    zhiShiKuFenDuan: '知识库分段',
    gengXinYu: '更新于',
    ziFu: '字符',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '最近更新于',
    chaKanZhiShiKu: '查看知识库',
    gengXinZhiShiKu: '更新知识库',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: '市场中公开',
  },
  BotCard: {
    guanBi: '关闭',
    maShanChuHouJiang: '」 吗？删除后将无法恢复，请谨慎操作。',
    queRenYaoShanChu: '确认要删除 「',
    gengXinZhiShi: '更新知识',
    gengXinZhiShiKu: '更新知识库(Coming Soon)',
    tiaoShi: '调试',
  },
  CreateButton: {
    chuangJianTOK: '创建 Token',
  },
  CreateModal: {
    miYao: '密钥',
    miYao2: '密钥*',
    geiTOKE: '给 Token 取一个独一无二的标识',
    miYaoBiaoShi: '密钥标识*',
  },
  Crash: {
    qingChangShiShuaXin: '请尝试刷新浏览器',
    woMenSiHuYu: '我们似乎遇到了一些导致崩溃的问题',
  },
  Navbar: {
    chuangJianJiQiRen: '创建机器人',
    qingShuRuKaPian: '请输入卡片名称',
    kongJian: '空间',
    shiChang: '市场',
  },
  PublishBotEntity: {
    shangJiaJiQiRen: '上架机器人',
    zanWuWeiShangJia: '暂无未上架的机器人',
    xuanZeJiQiRen: '选择机器人',
    geiWoMenTiYi: '给我们提一个 Issue，留下您的机器人信息',
    iSSUE: 'Issue 区',
    cOMIN: 'coming soon, 请先前往 GitHub',
    shangJiaShiBaiE: '上架失败{val1}',
    shangJiaChengGong: '上架成功',
  },
  User: {
    dengChu: '登出',
    tOKEN: 'Token 管理',
    dengLu: '登录',
  },
};
