export default {
  BotCreateFrom: {
    queRen: 'Confirm',
    quXiao: 'Cancel',
    ma: '?',
    ninZhenDeRenXin: 'Are you sure you want to delete',
    shanChuJiQiRen: 'Delete bot',
    weiXianCaoZuo: 'Dangerous operation',
    kaiChangBaiYuZhi: 'Opening preset questions',
    shuRuKaiChangWen: 'Enter the opening text',
    kaiChangBaiWenAn: 'Opening text',
    kaiChangBai: 'Opening statement',
    shiYongPET: 'Use the token provided by petercat',
    guanFang: 'Official',
    xuanZeTOK: 'Select token',
    xuanZeDaMoXing: 'Select large model',
    daMoXing: 'Large model',
    renSheYuHuiFu: 'Character and reply logic',
    jianDanMiaoShuJi: 'Briefly describe the bot’s purpose',
    jiQiRenMiaoShu: 'Bot description*',
    geiJiQiRenQi: 'Give the bot a unique name',
    jiQiRenMingCheng: 'Bot name*',
    gITHU: 'GitHub avatar',
    suiJiTouXiang: 'Random avatar',
    jiQiRenTouXiang: 'Bot avatar*',
    ziDingYi: 'Custom',
    shanChuShiBaiE: 'Deletion failed',
    shanChuChengGong: 'Deletion successful',
  },
  InputList: {
    shanChu: 'Delete',
    shuRuKaiChangBai: 'Enter the guided question for the opening statement',
  },
  Knowledge: {
    zhiShiKuWeiKong: 'Knowledge base is empty',
    zhiShiKuGengXin: 'Knowledge base updating',
    zhiShiKuFenDuan: 'Knowledge base segmentation',
    gengXinYu: 'Updated at',
    ziFu: 'Characters',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: 'Last updated at',
    chaKanZhiShiKu: 'View knowledge base',
    gengXinZhiShiKu: 'Update knowledge base',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: 'Public in the marketplace',
  },
  BotCard: {
    guanBi: 'Close',
    maShanChuHouJiang:
      '”? Once deleted, it cannot be restored, please proceed with caution.',
    queRenYaoShanChu: 'Confirm to delete "',
    gengXinZhiShi: 'Update knowledge',
    gengXinZhiShiKu: 'Update knowledge base (Coming Soon)',
    tiaoShi: 'Debug',
  },
  CreateButton: {
    chuangJianTOK: 'Create Token',
  },
  CreateModal: {
    miYao: 'Secret Key',
    miYao2: 'Secret Key*',
    geiTOKE: 'Give the token a unique identifier',
    miYaoBiaoShi: 'Secret Key Identifier*',
  },
};
