export default {
  BotCreateFrom: {
    queRen: 'Confirm',
    quXiao: 'Cancel',
    ma: '?',
    ninZhenDeRenXin: 'Are you sure you want to delete',
    shanChuJiQiRen: 'Delete Bot',
    weiXianCaoZuo: 'Dangerous Operation',
    kaiChangBaiYuZhi: 'Preset Opening Questions',
    shuRuKaiChangWen: 'Enter Opening Text',
    kaiChangBaiWenAn: 'Opening Text',
    kaiChangBai: 'Opening',
    shiYongPET: 'Use token provided by petercat',
    guanFang: 'Official',
    xuanZeTOK: 'Select Token',
    xuanZeDaMoXing: 'Select Large Model',
    daMoXing: 'Large Model',
    renSheYuHuiFu: 'Persona and Response Logic',
    jianDanMiaoShuJi: 'Briefly describe the purpose of the bot',
    jiQiRenMiaoShu: 'Bot Description*',
    geiJiQiRenQi: 'Give the bot a unique name',
    jiQiRenMingCheng: 'Bot Name*',
    gITHU: 'GitHub Avatar',
    suiJiTouXiang: 'Random Avatar',
    jiQiRenTouXiang: 'Bot Avatar*',
    ziDingYi: 'Custom',
    shanChuShiBaiE: 'Delete Failed ',
    shanChuChengGong: 'Delete Successful',
  },
  InputList: {
    shanChu: 'Delete',
    shuRuKaiChangBai: 'Enter Opening Guiding Question',
  },
  Knowledge: {
    zhiShiKuWeiKong: 'Knowledge is Empty',
    zhiShiKuGengXin: 'Knowledge Updating',
    zhiShiKuFenDuan: 'Knowledge Segmentation',
    gengXinYu: 'Updated on',
    ziFu: 'Characters',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: 'Last Updated on',
    chaKanZhiShiKu: 'View Knowledge Base',
    gengXinZhiShiKu: 'Update Knowledge Base',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: 'Public in Market',
  },
  BotCard: {
    guanBi: 'Close',
    maShanChuHouJiang:
      '」? This action cannot be undone, please proceed with caution.',
    queRenYaoShanChu: 'Are you sure you want to delete 「',
    gengXinZhiShi: 'Update Knowledge',
    gengXinZhiShiKu: 'Update Knowledge Base (Coming Soon)',
    tiaoShi: 'Debug',
    yiZaiTEX: 'Already deployed on {val1}',
    guanWang: 'Official website',
    gITHU: ' GitHub platform',
  },
  CreateButton: {
    chuangJianTOK: 'Custodial Token',
  },
  CreateModal: {
    miYao: 'Secret Key',
    miYao2: 'Secret Key*',
    geiTOKE: 'Give the Token a unique identifier',
    miYaoBiaoShi: 'Secret Key Identifier*',
  },
  Crash: {
    qingChangShiShuaXin: 'Please try refreshing the browser',
    woMenSiHuYu: 'We seem to have encountered some issues causing a crash',
  },
  Navbar: {
    chuangJianJiQiRen: 'Create Bot',
    qingShuRuKaPian: 'Please enter card name',
    kongJian: 'Space',
    shiChang: 'Market',
  },
  PublishBotEntity: {
    shangJiaJiQiRen: 'List Bot',
    zanWuWeiShangJia: 'No unlisted bots available',
    xuanZeJiQiRen: 'Select Bot',
    geiWoMenTiYi: 'Submit an Issue to us with your bot information',
    iSSUE: 'Issue Area',
    cOMIN: 'coming soon, please go to GitHub first',
    shangJiaShiBaiE: 'Listing Failed ',
    shangJiaChengGong: 'Listing Successful',
  },
  User: {
    dengChu: 'Logout',
    tOKEN: 'Token Management',
    dengLu: 'Login',
  },
};
