version = 0.1
[default.deploy.parameters]
stack_name = "{{YOUR_STACK_NAME}}"
resolve_s3 = true
s3_prefix = "{{YOUR_STACK_NAME}}"
region = "{{YOUR REGION}}"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
