export default {
  BotCreateFrom: {
    queRen: '確認',
    quXiao: 'キャンセル',
    ma: 'か？',
    ninZhenDeRenXin: '本当に削除しますか',
    shanChuJiQiRen: 'ボットを削除',
    weiXianCaoZuo: '危険な操作',
    kaiChangBaiYuZhi: '挨拶のプリセット質問',
    shuRuKaiChangWen: '挨拶文を入力',
    kaiChangBaiWenAn: '挨拶文',
    kaiChangBai: '挨拶',
    shiYongPET: 'petercatが提供するトークンを使用',
    guanFang: '公式',
    xuanZeTOK: 'トークンを選択',
    xuanZeDaMoXing: '大規模モデルを選択',
    daMoXing: '大規模モデル',
    renSheYuHuiFu: 'ペルソナと応答ロジック',
    jianDanMiaoShuJi: 'ボットの用途を簡単に説明してください',
    jiQiRenMiaoShu: 'ボットの説明*',
    geiJiQiRenQi: 'ボットにユニークな名前をつけてください',
    jiQiRenMingCheng: 'ボット名*',
    gITHU: 'GitHubアバター',
    suiJiTouXiang: 'ランダムアバター',
    jiQiRenTouXiang: 'ボットアバター*',
    ziDingYi: 'カスタム',
    shanChuShiBaiE: '削除失敗 ',
    shanChuChengGong: '削除成功',
  },
  InputList: {
    shanChu: '削除',
    shuRuKaiChangBai: '挨拶のガイド質問を入力',
  },
  Knowledge: {
    zhiShiKuWeiKong: 'ナレッジベースが空です',
    zhiShiKuGengXin: 'ナレッジベース更新中',
    zhiShiKuFenDuan: 'ナレッジベースのセグメンテーション',
    gengXinYu: '更新日',
    ziFu: '文字',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '最終更新日',
    chaKanZhiShiKu: 'ナレッジベースを表示',
    gengXinZhiShiKu: 'ナレッジベースを更新',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: 'マーケットで公開',
  },
  BotCard: {
    guanBi: '閉じる',
    maShanChuHouJiang: '」か？削除後は復元できません。慎重に操作してください。',
    queRenYaoShanChu: '「',
    gengXinZhiShi: '知識を更新',
    gengXinZhiShiKu: 'ナレッジベースを更新（近日公開）',
    tiaoShi: 'デバッグ',
    yiZaiTEX: '{val1} に展開済み',
    guanWang: '公式ウェブサイト',
    gITHU: ' GitHubプラットフォーム',
  },
  CreateButton: {
    chuangJianTOK: '托管されたトークン',
  },
  CreateModal: {
    miYao: 'シークレットキー',
    miYao2: 'シークレットキー*',
    geiTOKE: 'トークンにユニークな識別子を付けてください',
    miYaoBiaoShi: 'シークレットキー識別子*',
  },
  Crash: {
    qingChangShiShuaXin: 'ブラウザを更新してみてください',
    woMenSiHuYu: 'クラッシュの原因となる問題が発生したようです',
  },
  Navbar: {
    chuangJianJiQiRen: 'ボットを作成',
    qingShuRuKaPian: 'カード名を入力してください',
    kongJian: 'スペース',
    shiChang: 'マーケット',
  },
  PublishBotEntity: {
    shangJiaJiQiRen: 'ボットを公開',
    zanWuWeiShangJia: '公開されていないボットはありません',
    xuanZeJiQiRen: 'ボットを選択',
    geiWoMenTiYi: 'Issueを提出し、ボット情報を残してください',
    iSSUE: 'Issue エリア',
    cOMIN: '近日公開予定、まずはGitHubへ',
    shangJiaShiBaiE: '公開失敗',
    shangJiaChengGong: '公開成功',
  },
  User: {
    dengChu: 'ログアウト',
    tOKEN: 'トークン管理',
    dengLu: 'ログイン',
  },
  Header: {
    gengXinDaiMaCang: 'コードリポジトリを更新',
    zhiShiLieBiao: '知識リスト',
    bianJiJiQiRen: 'ボットを編集',
    gengXinDaiMaCang2: 'コードリポジトリの更新に失敗しました{val1}',
    chengGongGengXinDai: 'コードリポジトリを正常に更新しました',
  },
  KnowledgeList: {
    keYongZhuangTai: '利用可能状態',
    daXiao: 'サイズ',
    xiangLiangHuaMoXing: 'ベクトルモデル',
    zhiShiLaiYuan: '知識ソース',
    leiXing: 'タイプ',
    zhiShiMing: '知識名',
  },
  TaskButton: {
    chaKanRenWu: 'タスク表示',
    chongXinZhiXing: '再実行',
    shiBai: '失敗',
    ruKuZhong: 'インポート中',
    dengDaiZhong: '待機中',
    chongShiSuoXuanRen: '選択したタスクを再試行',
  },
  TaskList: {
    meiYouChaXunDao: 'タスクが見つかりません',
  },
  ChunkList: {
    fenKuaiNeiRong: 'チャンクコンテンツ',
  }
};
