export default {
  BotCreateFrom: {
    queRen: '確認',
    quXiao: 'キャンセル',
    ma: 'ですか？',
    ninZhenDeRenXin: '本当に削除しますか',
    shanChuJiQiRen: 'ボットを削除',
    weiXianCaoZuo: '危険な操作',
    kaiChangBaiYuZhi: '開始メッセージのプリセット質問',
    shuRuKaiChangWen: '開始メッセージを入力',
    kaiChangBaiWenAn: '開始メッセージの文言',
    kaiChangBai: '開始メッセージ',
    shiYongPET: 'petercat提供のトークンを使用',
    guanFang: '公式',
    xuanZeTOK: 'トークンを選択',
    xuanZeDaMoXing: '大規模モデルを選択',
    daMoXing: '大規模モデル',
    renSheYuHuiFu: 'キャラクター設定と応答ロジック',
    jianDanMiaoShuJi: 'ボットの用途を簡単に説明',
    jiQiRenMiaoShu: 'ボットの説明*',
    geiJiQiRenQi: 'ボットにユニークな名前を付ける',
    jiQiRenMingCheng: 'ボット名*',
    gITHU: 'GitHubアバター',
    suiJiTouXiang: 'ランダムアバター',
    jiQiRenTouXiang: 'ボットのアバター*',
    ziDingYi: 'カスタマイズ',
    shanChuShiBaiE: '削除に失敗しました',
    shanChuChengGong: '削除に成功しました',
  },
  InputList: {
    shanChu: '削除',
    shuRuKaiChangBai: '開始メッセージの誘導質問を入力',
  },
  Knowledge: {
    zhiShiKuWeiKong: 'ナレッジベースが空です',
    zhiShiKuGengXin: 'ナレッジベースを更新中',
    zhiShiKuFenDuan: 'ナレッジベースの分割',
    gengXinYu: '更新日',
    ziFu: '文字数',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '最近の更新日',
    chaKanZhiShiKu: 'ナレッジベースを見る',
    gengXinZhiShiKu: 'ナレッジベースを更新',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: 'マーケットに公開',
  },
  BotCard: {
    guanBi: '閉じる',
    maShanChuHouJiang:
      '」ですか？削除後は復元できませんので、慎重に操作してください。',
    queRenYaoShanChu: '「を削除してよろしいですか？',
    gengXinZhiShi: '知識を更新',
    gengXinZhiShiKu: 'ナレッジベースの更新 (近日公開)',
    tiaoShi: 'デバッグ',
  },
  CreateButton: {
    chuangJianTOK: 'トークンを作成',
  },
  CreateModal: {
    miYao: '秘密鍵',
    miYao2: '秘密鍵*',
    geiTOKE: 'トークンにユニークな識別子を付ける',
    miYaoBiaoShi: '秘密鍵識別子*',
  },
};
