export default {
  BotCreateFrom: {
    queRen: '確認',
    quXiao: '取消',
    ma: '嗎？',
    ninZhenDeRenXin: '您真的忍心刪除',
    shanChuJiQiRen: '刪除機器人',
    weiXianCaoZuo: '危險操作',
    kaiChangBaiYuZhi: '開場白預置問題',
    shuRuKaiChangWen: '輸入開場文案',
    kaiChangBaiWenAn: '開場白文案',
    kaiChangBai: '開場白',
    shiYongPET: '使用 petercat 提供的 token',
    guanFang: '官方',
    xuanZeTOK: '選擇 token',
    xuanZeDaMoXing: '選擇大模型',
    daMoXing: '大模型',
    renSheYuHuiFu: '人設與回覆邏輯',
    jianDanMiaoShuJi: '簡單描述機器人的用途',
    jiQiRenMiaoShu: '機器人描述*',
    geiJiQiRenQi: '給機器人起一個獨一無二的名字',
    jiQiRenMingCheng: '機器人名稱*',
    gITHU: 'GitHub 頭像',
    suiJiTouXiang: '隨機頭像',
    jiQiRenTouXiang: '機器人頭像*',
    ziDingYi: '自定義',
    shanChuShiBaiE: '刪除失敗 ',
    shanChuChengGong: '刪除成功',
  },
  InputList: {
    shanChu: '刪除',
    shuRuKaiChangBai: '輸入開場白引導問題',
  },
  Knowledge: {
    zhiShiKuWeiKong: '知識庫為空',
    zhiShiKuGengXin: '知識庫更新中',
    zhiShiKuFenDuan: '知識庫分段',
    gengXinYu: '更新於',
    ziFu: '字元',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '最近更新於',
    chaKanZhiShiKu: '檢視知識庫',
    gengXinZhiShiKu: '更新知識庫',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: '市場中公開',
  },
  BotCard: {
    guanBi: '關閉',
    maShanChuHouJiang: '」嗎？刪除後將無法恢復，請謹慎操作。',
    queRenYaoShanChu: '確認要刪除「',
    gengXinZhiShi: '更新知識',
    gengXinZhiShiKu: '更新知識庫 (Coming Soon)',
    tiaoShi: '除錯',
    yiZaiTEX: '已在{val1}部署',
    guanWang: '官網',
    gITHU: ' GitHub 平臺',
  },
  CreateButton: {
    chuangJianTOK: '代管 Token',
  },
  CreateModal: {
    miYao: '金鑰',
    miYao2: '金鑰*',
    geiTOKE: '給 Token 取一個獨一無二的標識',
    miYaoBiaoShi: '金鑰標識*',
  },
  Crash: {
    qingChangShiShuaXin: '請嘗試重新整理瀏覽器',
    woMenSiHuYu: '我們似乎遇到了一些導致崩潰的問題',
  },
  Navbar: {
    chuangJianJiQiRen: '建立機器人',
    qingShuRuKaPian: '請輸入卡片名稱',
    kongJian: '空間',
    shiChang: '市場',
  },
  PublishBotEntity: {
    shangJiaJiQiRen: '上架機器人',
    zanWuWeiShangJia: '暫無未上架的機器人',
    xuanZeJiQiRen: '選擇機器人',
    geiWoMenTiYi: '給我們提一個 Issue，留下您的機器人資訊',
    iSSUE: 'Issue 區',
    cOMIN: 'coming soon, 請先前往 GitHub',
    shangJiaShiBaiE: '上架失敗',
    shangJiaChengGong: '上架成功',
  },
  User: {
    dengChu: '登出',
    tOKEN: 'Token 管理',
    dengLu: '登入',
  },
};
