export default {
  page: {
    jiQiRenShangWei: '機器人尚未配置任何內容    請在完成配置後進行對話測試',
    baoCun: '儲存',
    yuLanYuCeShi: '預覽與測試',
    shouDongPeiZhi: '手動配置',
    duiHuaTiaoShi: '對話除錯',
    chongXinShengChengPei: '重新生成配置',
    ziDongShengChengPei: '自動生成配置',
    diZhiYouWu: '地址有誤',
    qingShuRuGI: '請輸入或選擇 GitHub 專案名稱',
    fuZhiTOK: '複製 Token',
    tOKEN: 'Token 已複製到剪貼簿',
    gITHU: 'GitHub 專案名稱',
    bangWoPeiZhiYi: '幫我配置一個答疑機器人',
    chuCiJianMianXian:
      '👋🏻 初次見面，先自我介紹一下：我是 PeterCat，一個開源專案的機器人。你可以透過和我對話配置一個答疑機器人。',
    shengChengShiBai: '生成失敗',
    shengChengChengGongE: '生成成功',
    baoCunShiBaiE: '儲存失敗',
    baoCunChengGong: '儲存成功',
    shengChengShiBaiC: '生成失敗',
    shengChengChengGong: '生成成功',
    baoCunYuBuShu: '儲存與部署',
  },
};
