create table "public"."github_app_installations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "owner_name" text,
    "repo_name" text
);


create table "public"."user_rate_limit" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" text,
    "last_request" timestamp without time zone,
    "request_count" bigint
);


alter table "public"."user_rate_limit" enable row level security;

alter table "public"."github_repo_config" add column "owner_id" character varying;

alter table "public"."github_repo_config" add column "repo_id" character varying;

CREATE UNIQUE INDEX github_app_installations_pkey ON public.github_app_installations USING btree (id);

CREATE UNIQUE INDEX user_rate_limit_pkey ON public.user_rate_limit USING btree (id);

alter table "public"."github_app_installations" add constraint "github_app_installations_pkey" PRIMARY KEY using index "github_app_installations_pkey";

alter table "public"."user_rate_limit" add constraint "user_rate_limit_pkey" PRIMARY KEY using index "user_rate_limit_pkey";

grant delete on table "public"."github_app_installations" to "anon";

grant insert on table "public"."github_app_installations" to "anon";

grant references on table "public"."github_app_installations" to "anon";

grant select on table "public"."github_app_installations" to "anon";

grant trigger on table "public"."github_app_installations" to "anon";

grant truncate on table "public"."github_app_installations" to "anon";

grant update on table "public"."github_app_installations" to "anon";

grant delete on table "public"."github_app_installations" to "authenticated";

grant insert on table "public"."github_app_installations" to "authenticated";

grant references on table "public"."github_app_installations" to "authenticated";

grant select on table "public"."github_app_installations" to "authenticated";

grant trigger on table "public"."github_app_installations" to "authenticated";

grant truncate on table "public"."github_app_installations" to "authenticated";

grant update on table "public"."github_app_installations" to "authenticated";

grant delete on table "public"."github_app_installations" to "service_role";

grant insert on table "public"."github_app_installations" to "service_role";

grant references on table "public"."github_app_installations" to "service_role";

grant select on table "public"."github_app_installations" to "service_role";

grant trigger on table "public"."github_app_installations" to "service_role";

grant truncate on table "public"."github_app_installations" to "service_role";

grant update on table "public"."github_app_installations" to "service_role";

grant delete on table "public"."user_rate_limit" to "anon";

grant insert on table "public"."user_rate_limit" to "anon";

grant references on table "public"."user_rate_limit" to "anon";

grant select on table "public"."user_rate_limit" to "anon";

grant trigger on table "public"."user_rate_limit" to "anon";

grant truncate on table "public"."user_rate_limit" to "anon";

grant update on table "public"."user_rate_limit" to "anon";

grant delete on table "public"."user_rate_limit" to "authenticated";

grant insert on table "public"."user_rate_limit" to "authenticated";

grant references on table "public"."user_rate_limit" to "authenticated";

grant select on table "public"."user_rate_limit" to "authenticated";

grant trigger on table "public"."user_rate_limit" to "authenticated";

grant truncate on table "public"."user_rate_limit" to "authenticated";

grant update on table "public"."user_rate_limit" to "authenticated";

grant delete on table "public"."user_rate_limit" to "service_role";

grant insert on table "public"."user_rate_limit" to "service_role";

grant references on table "public"."user_rate_limit" to "service_role";

grant select on table "public"."user_rate_limit" to "service_role";

grant trigger on table "public"."user_rate_limit" to "service_role";

grant truncate on table "public"."user_rate_limit" to "service_role";

grant update on table "public"."user_rate_limit" to "service_role";


