export default {
  BotCreateFrom: {
    queRen: '확인',
    quXiao: '취소',
    ma: '입니까?',
    ninZhenDeRenXin: '정말로 삭제하시겠습니까',
    shanChuJiQiRen: '봇 삭제',
    weiXianCaoZuo: '위험한 작업',
    kaiChangBaiYuZhi: '시작 대사 프리셋 질문',
    shuRuKaiChangWen: '시작 문구 입력',
    kaiChangBaiWenAn: '시작 대사 문구',
    kaiChangBai: '시작 대사',
    shiYongPET: 'petercat 제공 토큰 사용',
    guanFang: '공식',
    xuanZeTOK: '토큰 선택',
    xuanZeDaMoXing: '대형 모델 선택',
    daMoXing: '대형 모델',
    renSheYuHuiFu: '캐릭터 설정 및 응답 논리',
    jianDanMiaoShuJi: '봇 용도 간단 설명',
    jiQiRenMiaoShu: '봇 설명*',
    geiJiQiRenQi: '봇에 고유한 이름 지정',
    jiQiRenMingCheng: '봇 이름*',
    gITHU: 'GitHub 아바타',
    suiJiTouXiang: '랜덤 아바타',
    jiQiRenTouXiang: '봇 아바타*',
    ziDingYi: '사용자 정의',
    shanChuShiBaiE: '삭제 실패',
    shanChuChengGong: '삭제 성공',
  },
  InputList: {
    shanChu: '삭제',
    shuRuKaiChangBai: '시작 대사 유도 질문 입력',
  },
  Knowledge: {
    zhiShiKuWeiKong: '지식 베이스가 비어 있습니다',
    zhiShiKuGengXin: '지식 베이스 업데이트 중',
    zhiShiKuFenDuan: '지식 베이스 분할',
    gengXinYu: '업데이트됨',
    ziFu: '문자',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '최근 업데이트됨',
    chaKanZhiShiKu: '지식 베이스 보기',
    gengXinZhiShiKu: '지식 베이스 업데이트',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: '시장에 공개',
  },
  BotCard: {
    guanBi: '닫기',
    maShanChuHouJiang:
      '」입니까? 삭제 후 복구할 수 없습니다. 신중히 진행하십시오.',
    queRenYaoShanChu: '「을(를) 삭제하시겠습니까?',
    gengXinZhiShi: '지식 업데이트',
    gengXinZhiShiKu: '지식 베이스 업데이트 (곧 출시 예정)',
    tiaoShi: '디버깅',
  },
  CreateButton: {
    chuangJianTOK: '토큰 생성',
  },
  CreateModal: {
    miYao: '비밀 키',
    miYao2: '비밀 키*',
    geiTOKE: '토큰에 고유한 식별자 지정',
    miYaoBiaoShi: '비밀 키 식별자*',
  },
};
