export default {
  BotCreateFrom: {
    queRen: '확인',
    quXiao: '취소',
    ma: '인가요?',
    ninZhenDeRenXin: '정말로 삭제하시겠습니까',
    shanChuJiQiRen: '봇 삭제',
    weiXianCaoZuo: '위험한 작업',
    kaiChangBaiYuZhi: '인사말 사전 설정 질문',
    shuRuKaiChangWen: '인사말 텍스트 입력',
    kaiChangBaiWenAn: '인사말 텍스트',
    kaiChangBai: '인사말',
    shiYongPET: 'petercat에서 제공하는 토큰 사용',
    guanFang: '공식',
    xuanZeTOK: '토큰 선택',
    xuanZeDaMoXing: '대형 모델 선택',
    daMoXing: '대형 모델',
    renSheYuHuiFu: '페르소나 및 응답 로직',
    jianDanMiaoShuJi: '봇의 용도를 간단히 설명하세요',
    jiQiRenMiaoShu: '봇 설명*',
    geiJiQiRenQi: '봇에 고유한 이름을 지어주세요',
    jiQiRenMingCheng: '봇 이름*',
    gITHU: 'GitHub 아바타',
    suiJiTouXiang: '랜덤 아바타',
    jiQiRenTouXiang: '봇 아바타*',
    ziDingYi: '사용자 정의',
    shanChuShiBaiE: '삭제 실패 ',
    shanChuChengGong: '삭제 성공',
  },
  InputList: {
    shanChu: '삭제',
    shuRuKaiChangBai: '인사말 안내 질문 입력',
  },
  Knowledge: {
    zhiShiKuWeiKong: '지식 베이스가 비어 있습니다',
    zhiShiKuGengXin: '지식 베이스 업데이트 중',
    zhiShiKuFenDuan: '지식 베이스 세그먼테이션',
    gengXinYu: '업데이트 날짜',
    ziFu: '문자',
  },
  KnowledgeBtn: {
    zuiJinGengXinYu: '최근 업데이트',
    chaKanZhiShiKu: '지식 베이스 보기',
    gengXinZhiShiKu: '지식 베이스 업데이트',
  },
  PublicSwitcher: {
    shiChangZhongGongKai: '마켓에 공개',
  },
  BotCard: {
    guanBi: '닫기',
    maShanChuHouJiang: '」 인가요? 삭제 후에는 복구할 수 없습니다. 신중하게 조작해 주세요.',
    queRenYaoShanChu: '「',
    gengXinZhiShi: '지식 업데이트',
    gengXinZhiShiKu: '지식 베이스 업데이트(Coming Soon)',
    tiaoShi: '디버그',
    yiZaiTEX: '{val1}에서 이미 배포됨',
    guanWang: '공식 웹사이트',
    gITHU: ' GitHub 플랫폼',
  },
  CreateButton: {
    chuangJianTOK: '토큰 생성',
  },
  CreateModal: {
    miYao: '비밀 키',
    miYao2: '비밀 키*',
    geiTOKE: '토큰에 고유한 식별자를 지정하세요',
    miYaoBiaoShi: '비밀 키 식별자*',
  },
  Crash: {
    qingChangShiShuaXin: '브라우저를 새로고침해 보세요',
    woMenSiHuYu: '충돌을 일으키는 문제가 발생한 것 같습니다',
  },
  Navbar: {
    chuangJianJiQiRen: '봇 생성',
    qingShuRuKaPian: '카드 이름을 입력하세요',
    kongJian: '공간',
    shiChang: '마켓',
  },
  PublishBotEntity: {
    shangJiaJiQiRen: '봇 등록',
    zanWuWeiShangJia: '등록되지 않은 봇이 없습니다',
    xuanZeJiQiRen: '봇 선택',
    geiWoMenTiYi: '이슈를 제출하고 봇 정보를 남겨주세요',
    iSSUE: '이슈 영역',
    cOMIN: '곧 제공 예정, 먼저 GitHub로 이동해 주세요',
    shangJiaShiBaiE: '등록 실패',
    shangJiaChengGong: '등록 성공',
  },
  User: {
    dengChu: '로그아웃',
    tOKEN: '토큰 관리',
    dengLu: '로그인',
  },
};
